### ISSUE TITLE
juicessh cannot use su command

### ISSUE THREAD

**Issue by bugme2** [bmax121/APatch#152] opened 2024-01-17 04:15 UTC
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] If patch failed, root failed, or device unable to boot after flashing the new boot.img. Please goto KernelPatch
- [X] I will upload bugreport file in APatch Manager - Settings - Report log
- [X] My problem is fully stated in English, no reference to outside forums
- [ ] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

![Screenshot_2024-01-17-12-05-02-33_3d419158bad5872c40592a6c9956e692](https://github.com/bmax121/APatch/assets/40169265/6cbf106c-f326-415e-88e0-05ff78204579)

### Device info

- Device: RMX1851
- OS Version: Android 11(RealmeUI 2.0)
- APatch Version: 10433
- Kernel Version: 0.8.4

**Comment by bugme2** [comment] 2024-01-17 06:21
还有MyAndroidTools也无法获取权限
![Screenshot_2024-01-17-14-20-24-00_26ccd656f4ada08d09da6514b90ed2c0](https://github.com/bmax121/APatch/assets/40169265/bf03c5f4-cf08-4956-8d38-03c1e44089b2)

**Comment by bmax121** [comment] 2024-01-17 14:21
upload logs in /data/adb/ap/log

**Comment by bugme2** [comment] 2024-01-17 15:57
> upload logs in /data/adb/ap/log

[log.zip](https://github.com/bmax121/APatch/files/13965528/log.zip)

**Comment by ponces** [comment] 2024-01-21 01:06
I have easily reproduced this issue and can confirm it.

I can also confirm that this is due to the fact that `su` is in fact being called using `/data/adb/apd` instead of `/system/bin/kp`.
Because of this, the `arg[0]` is not the one expected and that's why the root shell is not being invoked based on [this line](https://github.com/bmax121/APatch/blob/86e769850e4931ceffb312152a5403cb171c72f8/apd/src/cli.rs#L80).
@bmax121 should we consider `/data/adb/apd` on this `if` condition too or should we look into this in a different way?

**Comment by ponces** [comment] 2024-01-24 00:14
Fixed with #8d49ef3733b83d2aa6ef3390305eb996fb68c8fe.
Closed.

**Closed by ponces** 2024-01-24 00:14 UTC
