### ISSUE TITLE
Not working on Samsung phones

### ISSUE THREAD

**Issue by rajarshikhatua100** [bmax121/APatch#199] opened 2024-02-03 17:58 UTC
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] If patch failed, root failed, or device unable to boot after flashing the new boot.img. Please goto KernelPatch
- [X] I will upload bugreport file in APatch Manager - Settings - Report log
- [X] My problem is fully stated in English. 请使用英文，不然会被关闭。
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

After flashing the Apatch -ed boot image file the device is not booting up

### Device info

- Device: Samsung Galaxy M31
- OS Version:13
- APatch Version:10474
- Kernel Version:4.14
- KernelPatch Version:10474

**Comment by RafaeloxMC** [comment] 2024-02-07 20:59
According to Apatch telegram bot:
"apatch_samsung:
Why APatch gives bootloops in Samsung devices:
[](https://g.co/bard/share/d0502ae5b7e5)
*Fixable by disabling it in the kernel side"

**Comment by Fede2782** [comment] 2024-02-10 11:29
Duplicate of https://github.com/bmax121/APatch/issues/123.

By the way APatch doesn't work because of Knox DEFEX/RKP enabled in kernel which goes against rooting.

**Comment by RafaeloxMC** [comment] 2024-02-10 12:41
@Fede2782 i did post a link from the telegram bot, got removed tho :o

**Closed** 2024-02-17 14:35 UTC
